apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: llm-d-demo
spec:
  connectionConfig:
    url: 'https://redhat-ai-bootcamp.github.io/llm-d-charts/'
  name: LLM-D Demo Charts
